{% set name = "r-metadig" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NCEAS/metadig-r/archive/refs/tags/v0.2.1.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
   - r-base
   - r-digest
   - r-httr
   - r-xml2
  run:
   - r-base
   - {{ native }}gcc-libs         # [win]
   - r-digest
   - r-httr
   - r-xml2

test:
 commands:
    - $R -e "library('metadig')"           # [not win]
    - "\"%R%\" -e \"library('metadig')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ADMM
  license: GPL-3.0-or-later
  summary: Provides algorithms to solve popular optimization problems in statistics such as regression
    or denoising based on Alternating Direction Method of Multipliers (ADMM). See Boyd
    et al (2010) <doi:10.1561/2200000016> for complete introduction to the method.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    
extra:
  recipe-maintainers:
    - conda-forge/r
    - TanguyGen
